# ============================================
# PRODUCTION docker-compose configuration file
# ============================================

version: "3.1"

services:
  gpio:
    build: ./
    container_name: gpio
    ports:
      - 5100:5100
    networks:
      - back_data

networks:
  back_data:
    external: true
